name: LeanCon Deployment CI

on:
  push:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MAIL_API_USER: ${{ secrets.MAIL_API_USER }}
  MAIL_API_PASS: ${{ secrets.MAIL_API_PASS }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    
    - name: Let's go!
      run: echo 'Auf gehts!'
    
    - name: Get Code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: build and restart
      run: |
        npm i -D turbo
        npm i --workspace server @nestjs/serve-static @nestjs/config
        echo "DATABASE_URL=\"$DATABASE_URL\"" > .env
        echo "JWT_SECRET=\"$JWT_SECRET\"" >> .env
        echo "MAIL_API_USER=\"$MAIL_API_USER\"" >> .env
        echo "MAIL_API_PASS=\"$MAIL_API_PASS\"" >> .env
        npm run build:prod
        npm run db:prod:update
        pm2 stop lean-con
        pm2 start lean-con
        pm2 save
        