name: LeanCon Deployment CI

on:
  push:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - run: echo 'Auf gehts!'
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20
    - run: |
        npm i -D turbo
        npm i --workspace server @nestjs/serve-static @nestjs/config
        echo "DATABASE_URL=\"$DATABASE_URL\"" > .env
        echo "JWT_SECRET=\"$JWT_SECRET\"" >> .env
        npm run build:prod
        npm run db:prod:update
        pm2 stop lean-con
        pm2 start lean-con
        pm2 save
        